### PR TITLE
Update reference region investment cost assumptions for solar and wind technologies

### PR DESCRIPTION
**Pull request by measrainsey**
Update the assumed base year reference region investment costs for `solar_pv_ppl`, `solar_pv_RC`, and `wind_ppf` in the `tools.costs` module.

Currently, the base year reference region investment costs used in the `tools.costs` module come from the [NAM_technology_cost_input_20200507.xlsx file](https://github.com/iiasa/message_data/blob/dev/data/model/investment_cost/doc/NAM_technology_cost_input_20200507.xlsx). However, we have found that the costs for solar technologies are too high, likely because the data used in the spreadsheet is a little old (from 2019). Thus, for now we are changing the input data so that IEA WEO 2021 costs are used for the reference region's base year investment costs for `solar_pv_ppl` and `solar_pv_RC`, mapped to large scale solar and residential solar in the WEO dataset, respectively.

Additionally, when reviewing the cost assumptions for wind, we realized that the manually specified base year reference region cost for offshore wind (`wind_ppf`) was too high and did not match the value indicated in [NAM_technology_cost_input_20200507.xlsx](https://github.com/iiasa/message_data/blob/dev/data/model/investment_cost/doc/NAM_technology_cost_input_20200507.xlsx). So the value in the module's input data file has been updated to reflect the value derived in the spreadsheet. 

Finally, we also saw that currently the input data is assuming no cost reductions for `wind_ppf` across all scenarios (so all reduction categories have values `0` and all scenarios are assigned a reduction category of "low"). For now, I've changed the cost reduction assumptions for `wind_ppf` so that it follows the same reduction narrative as onshore wind (`wind_ppl`): meaning I copied over the same cost reduction values for the different categories and the same categories across scenarios.

To summarize, the changes made are:

- Remove manually specified base year reference region costs for `solar_pv_ppl` and `solar_pv_RC` so that 2021 IEA WEO costs are used for these technologies
- Fix the manually specified base year reference region cost for `wind_ppf`
- Update cost reduction rates for `wind_ppf` (both the reduction rate values and the scenarios) so that it follows the same narrative as `wind_ppl`

The following figures show the changes in costs for the impacted technologies (`solar_pv_ppl`, `solar_pv_RC`, and `wind_ppf`) in `R12_NAM`. 
inv-cost-comparison-2024-04_solar_pv_ppl
inv-cost-comparison-2024-04_solar_pv_RC
inv-cost-comparison-2024-04_wind_ppf

## How to review

For @macflo8 : Confirm that the changes to the costs look reasonable (can modify later as needed)

For @glatterf42 and/or @khaeru: Read the diff and note that the CI checks all pass.

## PR checklist

- [x] Continuous integration checks all ✅
- [x] Update doc/whatsnew.

### CODE REVIEW

**Comment by khaeru** [comment]
> Update doc/whatsnew.

@measrainsey to pontificate a little here, there are several ways to inform users (and ourselves) about changes like these:
1. You've written a thorough and detailed PR description here. This will remain accessible so long as GitHub and this repo exist.
2. The “What's new” item points here.
3. A user who clones the repo and looks at the `git blame` for the modified data files will be pointed to these commits and this PR.

I think these are complete and adequate—so well done. I'd just like to record that there are other imaginable options:

4. Header or inline comments in the data files that note the original source for various data points. I think this is especially helpful if others are later trying to trace, validate, and maybe update certain values, and when a file mixes data from 2 or more sources. They can do this via (3), but explicit comments are more direct and persist even when the file is not obtained with its Git history.
5. The “What's new” item (2) could be more verbose, for instance including your bullets under “the changes made” above.
6. Alternately, those bullets (5) or your entire description could be added to the documentation page for the code that uses these data; then (2) could include a specific link to an ReST anchor like "See ___ for details of the changes."

We don't have a rigid style or preference for these, rather we just encourage to think, "Will I/colleagues/other users be able to understand the provenance of this data in the future? How can I make that easier, more transparent?"

**Comment by measrainsey** [comment]
Thanks @khaeru ! I've added some details to the `doc/whatsnew` and another header comment in one of the CSV files.

To you point (6), of my TODOs is to add better documentation for the base year reference region cost assumptions in general, as this was brought up in issue #169 as well.

**Comment by khaeru** [comment]
@measrainsey you might rebase now that we have a workaround in #175.

**Comment by macflo8** [comment]
thanks @measrainsey for implementing the requested changes. the new base year values look good to me. in my view this PR is ready to be merged.

**Review by macflo8 — APPROVED** [review]
thanks @measrainsey for implementing the requested changes. the new base year values look good to me. in my view this PR is ready to be merged.

**Comment by khaeru** [comment]
I see there's a commit 
> Delete DEMAND.csv.gz and demand.csv.gz again as part of rebase

This is essentially a fix for #168, but the preference we discussed there was to remove (variable) DEMAND, and keep (parameter) demand.

We can either fix that on `main` separately and rebase this PR, or adjust here. No preference from me.

**Comment by measrainsey** [comment]
> I see there's a commit
> 
> > Delete DEMAND.csv.gz and demand.csv.gz again as part of rebase
> 
> This is essentially a fix for #168, but the preference we discussed there was to remove (variable) DEMAND, and keep (parameter) demand.
> 
> We can either fix that on `main` separately and rebase this PR, or adjust here. No preference from me.

Hey Paul, thanks for calling this out -- I was going to bring it up once I rebased again (because I suspect I would have to delete the `DEMAND`/`demand` files again). On my side, it's a little finnicky whether my git tracking will think it's uppercase `DEMAND` that's changed or lowercase `demand` that's changed. And if I keep any one of them in my local, I can never rebase completely. From what I can see though, it seems parameter demand has been renamed to `demand_MESSAGE.csv.gz`, so it should no longer clash with the original `demand` vs `DEMAND` and would still be in the repo no matter what?

**Comment by khaeru** [comment]
> parameter demand has been renamed to `demand_MESSAGE.csv.gz`, so it should no longer clash with the original `demand` vs `DEMAND` and would still be in the repo no matter what?

No—there exist simultaneously:
1. a MESSAGE parameter named demand.
2. a MACRO parameter named demand_MESSAGE.
3. a MACRO variable named DEMAND.

IOW (2) is not just a rename of (1) to avoid a conflict with (3).

> Or, should I keep both demand_MESSAGE.csv.gz and lowercase demand.csv.gz?

Yes, *we* should—but I don't think it's your responsibility here. Let me quickly make a separate PR to deal with that.

**Comment by measrainsey** [comment]
> > parameter demand has been renamed to `demand_MESSAGE.csv.gz`, so it should no longer clash with the original `demand` vs `DEMAND` and would still be in the repo no matter what?
> 
> No—there exist simultaneously:
> 
>     1. a MESSAGE parameter named demand.
> 
>     2. a MACRO parameter named demand_MESSAGE.
> 
>     3. a MACRO variable named DEMAND.
> 
> 
> IOW (2) is not just a rename of (1) to avoid a conflict with (3).
> 
> > Or, should I keep both demand_MESSAGE.csv.gz and lowercase demand.csv.gz?
> 
> Yes, _we_ should—but I don't think it's your responsibility here. Let me quickly make a separate PR to deal with that.

Great, thanks for clarifying! I've added "demand.csv.gz" back into this PR, so now if this PR merges then both "demand.csv.gz" and "demand_MESSAGE.csv.gz" would exist. Uppercase "DEMAND.csv.gz" would not be there after this PR merges but it seems that will be addressed in your new PR #181.

**Comment by khaeru** [comment]
Thanks for the quick review on #181!

You can try something like this:

- On `costs/solar-wind`: discard the two last commits related to #168. Multiple ways to do this:
  ```
  git rebase -i HEAD~3
  # and then edit to put `d` (drop) beside the two last commits
  ```
  or
  ```
  git reset --hard HEAD~2
  ```
- Rebase `costs/solar-wind` onto `main`. This should now proceed without file conflicts.
- Force-push `costs/solar-wind`.

**Comment by measrainsey** [comment]
Successfully rebased (now, "_DEMAND.csv.gz", "demand.csv.gz", and "demand_MESSAGE.csv.gz all exist in this branch as well). And all tests are passing 👍🏻

**Pull request merged**
