### PR TITLE
Update location of databases in CLI commands

### LINKED ISSUE #31: The location of the IIASA ENE databases is depricated
Adding one of the IIASA ENE databases such as the main or ‘production’ database, which are listed on the [ENE wiki](https://github.com/iiasa/ece/wiki/Databases), one need to use the following CLI commands

`$ ixmp platform add [PLATFORMNAME] jdbc oracle x8oda.iiasa.ac.at:1521/pIXMP2.iiasa.ac.at [USERNAME] [PASSWORD]` 

or in some cases 

`$ ixmp platform add [PLATFORMNAME] jdbc oracle x8oda.iiasa.ac.at:1521/pIXMP1.iiasa.ac.at [USERNAME] [PASSWORD]`

instead of the old command

`$ ixmp platform add [PLATFORMNAME] jdbc oracle gp3.iiasa.ac.at:1521:GP2 [USERNAME] [PASSWORD]`

as @peterkolp stated.

### PR DESCRIPTION
**Pull request by LauWien**
This PR updates the location of the databases in the CLI commands of the documentation. 
Closes #31. 

## How to review

- Read the diff and note that the CI checks all pass.
- Build the documentation and look at the page _Command-line interface_.

## PR checklist

- [ ] Continuous integration checks all ✅

### CODE REVIEW

**Comment by LauWien** [comment]
If I'm not mistaken, the failing tests seem to be the same reported issue as in the closed PR [#513 ](https://github.com/iiasa/message_ix/pull/513) from the [message_ix ](https://github.com/iiasa/message_ix) repository.

**Comment by khaeru** [comment]
I would instead favour changing these (and the preceding text) to something generic. This repo/package (message-ix-models) is the public/open source one. message_data is the place for information related to our particular IIASA/ECE modeling workflows. So perhaps the IIASA/ECE-specific database URLs can be added to a page like https://docs.messageix.org/projects/models-internal/en/latest/install.html, and a link from here to there.

**Comment by khaeru** [comment]
As discussed, this should be rolled into a PR that addresses iiasa/message_data#287. Once that's opened, this one can be closed without merging.

**Comment by khaeru** [comment]
Removed the review request and closing as this will be rolled into iiasa/message_data#312. @LauWien you can ask for Peter's input on that if there's any remaining confusion.

**Pull request closed without merging**
