### PR TITLE
Fix issue with materials and cooling CCS technologies becoming cheaper than non-CCS counterpart

### PR DESCRIPTION
**Pull request by measrainsey**
Very small PR to change how NH3 CCS technologies in materials module are mapped

@ywpratama noticed during ScenarioMIP review process that costs for NH3 CCS technologies were becoming cheaper than the non-CCS NH3 technologies. This issue happened before in #186, due to CCS technologies being mapped to a different WEO technology than its non-CCS counterpart, as well as having different cost reduction assumptions. At the time, only energy technologies existed within the costs tool, and this new issue pertains to materials/industry technologies.

In this case, because the NH3 CCS technologies were mapped to MESSAGE technology `igcc_ccs` and the non-CCS counterparts were mapped to `igcc`, this led to issues of their costs crossing. As a fix, now the NH3 CCS and non-CCS technologies are mapped to MESSAGE energy technology `igcc`. 

Because this issue is not ScenaripMIP-specific, I think this small fix should best be treated as a standalone PR, merged to main. Then, additional ScenarioMIP-specific changes related to the SSP cost reduction narratives for these technologies can be added in a separate branch (using the functionality added in #255). 

## How to review

@ywpratama and/or @macflo8: please check if issue of costs for NH3 CCS still persists

For @khaeru and/or @glatterf42 : Read the diff and note that the CI checks all pass.

## PR checklist

- [x] Continuous integration checks all ✅
- [x] Add or expand tests; coverage checks both ✅
- [x] ~Add, expand, or update documentation.~
- [x] Update doc/whatsnew.

### CODE REVIEW

**Review by glatterf42 — APPROVED** [review]
The changes are small, looking good. However, I'm wondering whether we could bake requirements such as this into our test suite somehow. This would avoid being reliant on accidental discovery.

**Comment by macflo8** [comment]
Wrote a small script to test with the materials wrapper that calls `create_cost_projections()` with a pre-defined config. It generates the cost output for each SSP (+ LED) and asserts that the difference between the respective ccs and non-ccs NH3 technology is greater than 0. I can confirm that this runs without an `AssertionError` on this branch.

@glatterf42  Something similar could be integrated into the test suite for all CCS technologies maybe.

```python
import ixmp
import message_ix
from message_ix_models.model.material.data_util import gen_te_projections


mp = ixmp.Platform("<platform-name>")
scen = message_ix.Scenario(mp, f"<scenario-name>", "<model-name>")

# SSP1-5
for i in range(1, 6):
    inv, fix = gen_te_projections(scen, f"SSP{i}", method="gdp")
    for tec in [i + "_NH3" for i in ["biomass", "coal", "gas", "fueloil"]]:
        non_ccs = (
            inv[inv["technology"] == tec]
            .drop(columns=["unit", "technology"])
            .set_index(["node_loc", "year_vtg"])
        )
        ccs = (
            inv[inv["technology"] == tec + "_ccs"]
            .drop(columns=["unit", "technology"])
            .set_index(["node_loc", "year_vtg"])
        )
        assert ccs.sub(non_ccs).le(0).all().all() == False
# LED scenario
inv, fix = gen_te_projections(scen, "LED", method="gdp")
for tec in [i + "_NH3" for i in ["biomass", "coal", "gas", "fueloil"]]:
    non_ccs = (
        inv[inv["technology"] == tec]
        .drop(columns=["unit", "technology"])
        .set_index(["node_loc", "year_vtg"])
    )
    ccs = (
        inv[inv["technology"] == tec + "_ccs"]
        .drop(columns=["unit", "technology"])
        .set_index(["node_loc", "year_vtg"])
    )
    assert ccs.sub(non_ccs).le(0).all().all() == False
```

**Review by macflo8 — APPROVED** [review]

**Comment by khaeru** [comment]
@measrainsey —the doc/whatsnew conflict arises from the changes in #225 that I mentioned in Slack. If you rebase you can resolve the conflict by putting your added line from this PR into this section: https://github.com/iiasa/message-ix-models/blob/c5e275c87832d4c6b9de6d8cf05fc60579981b07/doc/whatsnew.rst?plain=1#L54-L65

Please ping me if that's not clear.

**Comment by measrainsey** [comment]
Thanks @khaeru ! I rebased and added my edit to doc/whatsnew in the new section -- hope that looks okay!

Regarding merging, I quickly chatted with @glatterf42 and we discussed me trying to see if I can add tests similar to the code @macflo8 showed above. I will spend a little time tomorrow to see if I can (or should) add this test -- will report back if I think this can be saved as a later PR or if I want to add it onto this PR!

**Comment by measrainsey** [comment]
hi all, i've added a short test based on @macflo8's code that checks costs for CCS technologies vs their non-CCS variants. and perhaps good thing too because turns out the test failed for the cooling module 😅 so i've also pushed a commit to change the mapping of the CCS-based cooling technologies (i can check with @adrivinca if this is okay and change the cooling technologies' inputs later on if necessary but for now don't consider this a blocker to pass this PR)

if this new test looks good to all, then please consider all done and ready on my end, and if we can move forward with merging that'd be great -- thanks!

that being said, before the latest push, the macOS python 3.13 tests were failing here:

```
FAILED message_ix_models/tests/model/transport/test_report.py::test_plot_simulated[stock-ldv] - genno.core.exceptions.MissingKeyError: required keys (<fuel economy:nl-m:ldv+ref>,) not defined
```

**Comment by measrainsey** [comment]
all tests are passing now so if everything looks good, would be great if we can move forward with merging 🙏🏻

**Comment by khaeru** [comment]
This appears all checked, approved, and green, so I'll merge.

**Pull request merged**
