### PR TITLE
Clean up Materials migration branch

### PR DESCRIPTION
**Pull request by macflo8**
This separate branch includes commits to tidy and make MESSAGEix-Materials run on message-ix-models.

## How to review

1. Check the removed files and changed code pieces
2. Build-Solve-Report MESSAGEix-Materials

## PR checklist

~- [ ] Continuous integration checks all ✅~ Not possible due to missing tests
- ~- Add or expand tests; coverage checks both ✅~ See https://github.com/iiasa/message-ix-models/pull/189#issuecomment-2128709498; will be handled via #194 
- [x] Add, expand, or update documentation.
- [x] Update doc/whatsnew.

### CODE REVIEW

**Comment by khaeru** [comment]
@macflo8, this and #188 look good, thank you!

One thing I notice is that the commit messages do not conform to our [code style](https://docs.messageix.org/en/latest/contributing.html#code-style) (see the first bullet).

For this `-tidy` branch with a few commits, it is easy to `git rebase -i` and use the `r`/`reword` command to adjust.

**Comment by glatterf42** [comment]
@macflo8, I've migrated the required functions now and cleaned up several imports. However, there's still work left to be done: the code quality check (as you analyzed) should be the first, but you also have a `doc.rst` file in `message_ix_models/model/material`. These files should generally live under `doc/`, in this case probably `doc/material` (since we also have `doc/water`. This file in particular is calling `automodule` for several `message_data.model.material` functions. These should all be migrated now, so please adapt to the new locations.

**Comment by macflo8** [comment]
Thanks, @glatterf42 for taking care of that 🙏🏻 I will have a look at the materials docs.

**Comment by macflo8** [comment]
The materials doc file is now moved and the code quality checks are passing. Do you agree to merge this PR @khaeru @glatterf42 ?

**Comment by khaeru** [comment]
Looking at [step (9) in our migration guide](https://docs.messageix.org/projects/models/en/latest/migrate.html#migrate-individual-modules-using-git-filter-repo):

> 9. Merge the clean-up branch from (7) into (6), and then (6) into `main`.

… I see the following things:
- The base PR #188 is still in a draft state.
- The base PR checklist has unchecked items.
- The base PR shows the message “This branch is out-of-date with the base branch” —it should be updated by rebasing `migrate-materials_2024-W17` on to `main`, and then rebasing this `migrate-materials_2024-W17-tidy` on to `migrate-materials_2024-W17`.
- The current PR shows "This branch cannot be rebased due to conflicts". The above step might make this go away.
- The current PR checklist has unchecked items, and some items are missing without comment.
- Per my earlier comment about commit messages, there are still some like:
  - “resolve conflict 2”
  - “resolve rebase conflict”
  - “resolve rebase conflict 3”
  
  (Many others still use the passive voice, like “Sets added”, but I guess this could be tolerated.)

Once we address these items, then we can make a simultaneous approval of *both* PRs, and then perform step (9).

**Comment by macflo8** [comment]
Thanks @khaeru!

- The base PR is now up to date with main
- The clean-up PR is also rebased
- I adjusted the PR checklist as discussed earlier today. I was not sure about the "Update doc/whatsnew". Should we update this?
- The unused files mentioned in @glatterf42's comment https://github.com/iiasa/message-ix-models/pull/188#issuecomment-2078684769 are now removed
- The mentioned commit messages have been rewritten to comply with the standard

**Comment by khaeru** [comment]
> * I was not sure about the "Update doc/whatsnew". Should we update this?

Please have a look at [these past commits](https://github.com/iiasa/message-ix-models/commits/main/doc/whatsnew.rst) to the file, particularly [this one](https://github.com/iiasa/message-ix-models/commit/676ca9f14a1a16dfae2305f112280898b3ced170) and [this one](https://github.com/iiasa/message-ix-models/commit/76bbbf6e794fd26d40cb93d1056aa3b4fde6594b). Something similar and short should be fine.

Please add the commit to this branch; then it will automatically be included for #188 as well.

**Comment by glatterf42** [comment]
Thanks, this is looking good now. Please open a new issue to mention and track that the materials team will provide tests at a later date (ideally within a few weeks or months).

@khaeru, would we want to exclude the new files from coverage (to keep the test coverage apparently high) or are we fine with the reduction in coverage (as we were for the nexus module)?

Either way, I think we can then approve this PR and merging this branch to the first migration branch hopefully resolves the code quality issues there, too.

**Comment by khaeru** [comment]
> @khaeru, would we want to exclude the new files from coverage (to keep the test coverage apparently high) or are we fine with the reduction in coverage (as we were for the nexus module)?

I think we ought to be honest, so better to accept the reduction.

**Comment by macflo8** [comment]
The tracking issue for tests and other pending items is now linked in the PR checklist. I will merge the PR once you approve @glatterf42 @khaeru.

**Review by khaeru — APPROVED** [review]
Please go ahead!

We should use the "merge commit" strategy for both PRs (i.e. not squash-and-merge or rebase-and-merge).

Once this one is merged, we will see the CI on #188 re-run and should check for the same outcome we currently see here.

**Pull request merged**
