### PR TITLE
Add MESSAGEix-Materials module

### PR DESCRIPTION
**Pull request by GamzeUnlu95**
This PR migrates .model.material (i.e. MESSAGEix-Materials) from the (private) message_data repo to this message-ix-models package, following the procedure described in https://github.com/iiasa/message-ix-models/pull/89.

## How to review

- Read the diff and note that the CI checks all pass.
- Run the build, solve, and report commands as described in the documentation. 
- Build the documentation and check if the page looks decent. 
- Ensure that changes/additions are self-documenting, i.e. that another
  developer (someone like the reviewer) will be able to understand what the code
  does in the future.

## PR checklist
- [ ] Continuous integration checks all ✅
- [ ] Add or expand tests; coverage checks both ✅
- [ ] Update doc/whatsnew.

### CODE REVIEW

**Comment by glatterf42** [comment]
Hi @GamzeUnlu95, thanks for this PR :)
Did you know that the tools that perform the Code quality Test can be set up to run automatically, so that you don't really have to think about them again and this test doesn't slow down your workflow? If you tell me which editor you are using, I can help you with that :)

**Comment by khaeru** [comment]
@macflo8 @GamzeUnlu95 @glatterf42 as I understand, this was superseded by #188 and #189.

The key question is: is there anything remaining on this branch that was *not* included in those PRs, yet should be preserved on `main`?

- If yes, I would suggest to mention as 1 or more comments/checklist items on #194.
  - These could be linked to this branch, or their original location on a message_data branch.
- Whether yes or no, we can then close this PR (without merging), and possibly delete the associated branch.

**Comment by macflo8** [comment]
I think there are no changes that need to be carried over from this branch, but I will check and confirm whether we can close this PR or need to add items to #194.

**Comment by khaeru** [comment]
As discussed at today's MESSAGE meeting:

- This branch is marked as archived (no deletion, no pushes, etc.) using [this rule](https://github.com/iiasa/message-ix-models/settings/rules/2007686).
- We will record the existence of the PR/branch for future reference, in case there is a need to come back to it: https://github.com/iiasa/message-ix-models/pull/218#issuecomment-2376406132

**Pull request closed without merging**
