### PR TITLE
Add node code lists R17 and R20

### PR DESCRIPTION
**Pull request by SiddharthJoshi-Git**
This PR adds two new regional mappings for GUIDE project and YSSP'23 work related to it. The R17 regional mapping is for YSSP work and R20 for overall GUIDE project.

## How to review

- Read the diff and note that the CI checks all pass.
- Confirm the new lists appear in the documentation.
- More TBA.

## PR checklist

- [x] Continuous integration checks all ✅
  
- [x] Add or expand tests; coverage checks both ✅
- [x] Add, expand, or update documentation.
- [x] Update doc/whatsnew.

### CODE REVIEW

**Comment by SiddharthJoshi-Git** [comment]
Hi @khaeru 

I opened a new #PR109 which superseded #PR108. The issue with `licensing error from GAMS` is now resolved, but the tests are fialing due to hardcoded list of `"expected"` node codelist within the` /data/node `folder. Especially this `message_ix_models/tests/model/test_structure.py`. Now the question is if I modify the test_structure.py file to include the new node code lists within this PR, will the test pass?

**Comment by glatterf42** [comment]
Hi @SiddharthJoshi-Git, it looks to me like you have to edit [doc/pkg-data/node.rst](https://github.com/iiasa/message-ix-models/blob/main/doc/pkg-data/node.rst) manually, but (following the other files), including all data from your R17.yaml file shouldn't take more than a few lines.

**Comment by khaeru** [comment]
> The only thing left is to update the docs for node code list.

Please re-read above:

> I would also ask that you update the `test_nodes()` function in the same file with cases that check that contents of the two new code lists.

**Comment by SiddharthJoshi-Git** [comment]
> Hi @SiddharthJoshi-Git, it looks to me like you have to edit [doc/pkg-data/node.rst](https://github.com/iiasa/message-ix-models/blob/main/doc/pkg-data/node.rst) manually, but (following the other files), including all data from your R17.yaml file shouldn't take more than a few lines.

Thanks @glatterf42, I will update this today manually.

**Comment by SiddharthJoshi-Git** [comment]
> > The only thing left is to update the docs for node code list.
> 
> Please re-read above:
> 
> > I would also ask that you update the `test_nodes()` function in the same file with cases that check that contents of the two new code lists.

Many thanks @khaeru . I have now added a new commit https://github.com/iiasa/message-ix-models/pull/109/commits/6729d9faf467d841dfbb08d99ca7c4998f726ac4 which parametrises checks for test_node() function. I hope this concludes the PR checks.

Based on @glatterf42 comment 
`Hi @SiddharthJoshi-Git, it looks to me like you have to edit [doc/pkg-data/node.rst](https://github.com/iiasa/message-ix-models/blob/main/doc/pkg-data/node.rst) manually, but (following the other files), including all data from your R17.yaml file shouldn't take more than a few lines.`

I will now proceed to add the node code lists to the .rst file

**Comment by SiddharthJoshi-Git** [comment]
Dear @khaeru, @glatterf42 

The PR is now ready for merging. 

Many thanks for your time.

Best,
Sid

**Comment by khaeru** [comment]
@SiddharthJoshi-Git thanks! At least a couple things remain:

- Please see [the code style](https://docs.messageix.org/en/stable/contributing.html#code-style) that applies to all the packages in our message_ix stack, particularly the "7 rules of a great Git commit message". If you like, you can e.g. `git rebase --interactive HEAD~8` on your local branch and use the `r`/`reword` command to apply this style to the commit messages. Otherwise, the PR can eventually be merged by the "squash-and-merge" method, i.e. as a single commit.
- Please check the boxes in the "PR checklist" in the template above if the things described are done. At a glance, it seems like you have not updated doc/whatsnew; see  iiasa/message-ix-models@b275f4d for a similar example.

**Comment by SiddharthJoshi-Git** [comment]
> @SiddharthJoshi-Git thanks! At least a couple things remain:
> 
> * Please see [the code style](https://docs.messageix.org/en/stable/contributing.html#code-style) that applies to all the packages in our message_ix stack, particularly the "7 rules of a great Git commit message". If you like, you can e.g. `git rebase --interactive HEAD~8` on your local branch and use the `r`/`reword` command to apply this style to the commit messages. Otherwise, the PR can eventually be merged by the "squash-and-merge" method, i.e. as a single commit.
> * Please check the boxes in the "PR checklist" in the template above if the things described are done. At a glance, it seems like you have not updated doc/whatsnew; see  [b275f4d](https://github.com/iiasa/message-ix-models/commit/b275f4d) for a similar example.

Many Thanks @khaeru,

For _suggestion 1_, I am ok with `squash and merge` strategy as the atomic commits on this PR are just for verification and not required after merge. Additionally, I must admit that I have not done` rebase/reword` before and hence I am afraid that I will mess-up something along the way. I have taken note of the resource `"7 rules of a great Git commit message"` and will apply the rules on next PR.

For _suggestion 2_, I have modified the `whatsnew.rst` via [af04b2d](https://github.com/iiasa/message-ix-models/pull/109/commits/af04b2da0615d09d5bf192484bf6919e78eafd64)

**Review by khaeru — APPROVED** [review]
Excellent, thanks for a complete & clean PR @SiddharthJoshi-Git. LGTM!

**Pull request merged**
